repos:
  -   repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
        -   id: black
            args: [--safe]
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
        -   id: debug-statements
            language_version: python3
  -   repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.0.269
      hooks:
        -   id: ruff
            args: [--fix]
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.3.0
      hooks:
        -   id: mypy
            args: [--no-strict-optional, --ignore-missing-imports]
